console.log('Content script loaded');

// Function to check if the compose window is open
function isComposeWindowOpen() {
  const composeWindow = document.querySelector('div[aria-label="New Message"]');
  
  if (composeWindow !== null) {
    console.log("Compose Window Open!");
  } else {
    console.log("Compose Window Not Open!");
  }

  return composeWindow !== null;
}

// Function to add the ChatGPT button
function addChatGptButton() {
  const composeButton = document.querySelector('div[aria-label="New Message"]');
  
  if (composeButton && !document.getElementById("chatGptButton")) {
    const button = document.createElement("button");
    button.id = "chatGptButton";
    button.innerText = "ChatGPT Draft";
    button.style.position = "absolute";
    button.style.bottom = "10px";
    button.style.right = "10px";
    button.style.padding = "10px";
    button.style.backgroundColor = "#34b7f1";
    button.style.color = "white";
    button.style.borderRadius = "5px";
    button.style.cursor = "pointer";

    button.addEventListener("click", function() {
      try {
        chrome.storage.sync.get(["apiKey"], function(result) {
          if (chrome.runtime.lastError) {
            console.error("Error accessing storage: ", chrome.runtime.lastError);
            alert("An error occurred while retrieving the API key.");
            return;
          }

          if (result.apiKey) {
            const context = document.querySelector('div[aria-label="Message Body"]').innerText;
            getChatGptResponse(context, result.apiKey);
          } else {
            alert("Please set your OpenAI API key in the extension settings.");
          }
        });
      } catch (error) {
        console.error("Error while adding ChatGPT button: ", error);
        alert("An unexpected error occurred. Please try again.");
      }
    });

    composeButton.appendChild(button);
  }
}

// Check and add the button only once when the compose window is detected
function checkAndAddButton() {
  if (isComposeWindowOpen()) {
    addChatGptButton();
  }
}

// Run the function to check the compose window status and add the button every 2 seconds
setInterval(checkAndAddButton, 2000);

// Function to call ChatGPT API with retry logic (handling rate limit error)
function getChatGptResponse(context, apiKey, retryCount = 0) {
  fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: "gpt-3.5-turbo", // or gpt-4
      messages: [
        { role: "system", content: "You are a helpful assistant." },
        { role: "user", content: context }
      ],
      max_tokens: 150,
    }),
  })
    .then((response) => {
      if (response.status === 429) {
        if (retryCount < 5) {
          // Exponential backoff for rate limit
          const retryDelay = Math.pow(2, retryCount) * 1000; // Delay doubles each time
          console.log(`Rate limit exceeded. Retrying in ${retryDelay / 1000} seconds...`);
          setTimeout(() => getChatGptResponse(context, apiKey, retryCount + 1), retryDelay);
        } else {
          alert("Exceeded the maximum number of retries. Please try again later.");
        }
      } else if (response.ok) {
        return response.json();
      } else {
        throw new Error(`Unexpected status: ${response.status}`);
      }
    })
    .then((data) => {
      // Ensure the response is valid before accessing 'choices'
      if (data && data.choices && data.choices.length > 0) {
        const subject = "Generated by ChatGPT";
        const body = data.choices[0].message.content.trim();
        setGmailDraft(subject, body);
      } else {
        alert("No response from ChatGPT. Please try again.");
      }
    })
    .catch((error) => {
      console.error("Error:", error);
      if (error.message.includes('choices')) {
        alert("Failed to get a response from ChatGPT. The API response was invalid.");
      } else {
        alert("Failed to get a response from ChatGPT. Please check your API key or try again later.");
      }
    });
}

// Function to update Gmail draft with the generated content
function setGmailDraft(subject, body) {
  document.querySelector('input[name="subjectbox"]').value = subject;
  document.querySelector('div[aria-label="Message Body"]').innerText = body;
}
